### ISSUE TITLE
specifications concerning homePage/landingPage

### ISSUE THREAD

**Issue by bfrichet3** [belgif/inspire-dcat#17]
It is not possible to handle multlingualism with homePage and landingPage attributes as we specified our profile. Therefore we should follow Bart's recommandation.

![image](https://user-images.githubusercontent.com/80756452/173100027-9f381cdc-6407-4830-92d3-e436bad8e5d7.png)

**Comment by celinevil** [comment]
OK. we will specify that for the use of these attributes

**Comment by barthanssens** [comment]
Might be more difficult: (Geo)DCAT-AP specifies a cardinality of 0..1 for dct:license (accessURL is 0..n), so validators (and/or portals using DCAT-AP) might flag multiple licenseDocument as an error

**Comment by bfrichet3** [comment]
@barthanssens maybe I should introduce a ticket on the european github because I think most of federal licenses are written in French and Dutch (I don't think English versions are legally binding)

**Comment by bfrichet3** [comment]
@celinevil We should reconsider the license attribute in the dcat:Catalog class

**Comment by barthanssens** [comment]
> 



>  maybe I should introduce a ticket on the european github because I think most of federal licenses are written in French and Dutch (I don't think English versions are legally binding)

Hmz, it's more complicated, since license is often used in e.g. faceted search, so having one single URI is helpful.
What might be a more interesting route here is using the FRBR approach also used by ELI (where LicenseDocument would b a "work", and each language an "expression"... somewhat similar to the relation between Dataset and Distribution)
